# Configuration file for DirExplorer

# After initilization, these settings cannot be changed without 
# a program restart
[Server]
# Directory to serve
Dir = "example/"

# Port to serve on
# (!) This has to be a string; you must enclose this number in quotes (!)
Port = "8080"

# Settings past this point can be changed live
[Header]

# Show the header or not
Show = true

# Main text (title)
Text = "NYXNET"

# Subtext 
Subtext = "Welcome to the NYXNET"

[Footer]

Show = true

Text = "DirExplorer PA1"

[Footer.Link]
Text = "Source"
Href = "https://github.com/TogoorooDev/DirExplorer"

# If you don't know what these settings do, leave them alone
[Caching]

#Settings for filename caching
[Caching.Filenames]

#Self Explanitory
Enable = true
