# Configuration file for DirExplorer

[Server]
# Directory to serve
Dir = "example/"

# Port to serve on
# (!) This has to be a string; you must enclose this number in quotes (!)
Port = "8080"


[Header]

# Show the header of not
Show = true

# Main text (title)
Text = "NYXNET"

# Subtext 
Subtext = "Welcome to the NYXNET"

[Footer]

Show = true

Text = "DirExplorer PA1"

[Footer.Link]
Text = "Source"
Href = "https://github.com/TogooroDev/DirExplorer"

#[Footer.Link]
#Text = "License"
#Href = "https://www.gnu.org/licenses/agpl-3.0.en.html"

#[Footer.Link]
#Text = "Home Page"
#Href = "/"
