# Configuration file for DirExplorer

# After initilization, these settings cannot be changed without 
# a program restart
[Server]
# Directory to serve
Dir = "example/"

# Port to serve on
# (!) This has to be a string; you must enclose this number in quotes (!)
Port = "8080"

# This must be a .ico file
Favicon = "static/default-favicon.ico"

# Settings past this point can be changed live
[Header]

# Show the header of not
Show = true

# Main text (title)
Text = "Cats"

# Subtext 
Subtext = "Cat Files!"

[Footer]

Show = true

Text = "DirExplorer IA2"

[Footer.Link]
Text = "Source"
Href = "https://github.com/TogoorooDev/DirExplorer"

# If you don't know what these settings do, leave them alone
[Caching]

#Settings for filename caching
[Caching.Filenames]

#Self Explanitory
Enable = false
